#import "lib/common.typ": agentName, course
#import "lib/reportLib.typ": docBody, firstPage, indexPage

#firstPage(agentName)

#indexPage()

#docBody[
  // #figure(
  //   image(
  //     "path",
  //     width: 50%,
  //   ),
  //   caption: [test],
  // )

  // #figure(
  //   table(
  //     columns: (50%, 50%),
  //     [], [],
  //   ),
  //   caption: [test],
  // )

  = BDI Agent

  The BDI agent is composed by a class dedicated to manage its beliefs, a set of classes to define the intentions and plans, and the actual `bdi_agent.js` that implements the beliefs set up and update, intention revision, intention storage and plan execution.

  == Beliefs

  == Intentions

  We defined the following types of intentions that the agent can create according to its beliefs.

  - *GoToIntention* - the desire of reaching a specific tile.

  - *GoPickUpIntention* - the desire of picking up a parcel at a specific tile.

  - *GoPutDownIntention* - the desire of deliverying all the parcel the agent is carrying on a specific red tile.

  - *DeviateAndPickUpIntention* - the desire of picking up a parcel while the agent is going to put down others. In some cases the agent can pick up a parcel that will increase the score with a simple small change in the path, without wasting much time.

  - *DeviateUsingPlannerIntention* - the desire of requesting to the planner a new path, because the one selected by the agent is no more practicable. The planner involvement is explained in details in @sec-planner.

  - *DeviateUsingAStarIntention* - the desire of requesting to the internal $A^*$ algorithm a new path, because the one selected by the agent is no more practicable.

  Besides BDI agent intentions, generated by the agent itself, also the LLM agent (explained in details in @sec-llm), can provide the following new intentions.

  - *LLMGoToIntention*

  - *LLMGoPutDownIntention*

  - *LLMGreenRedLightIntention*

  A queue is defined in order to store the pairs of selected intentions and the corresponding plans. The first element of the queue is executed by the agent.

  After the beliefs are set, an interval of 100 milliseconds generates a new intention, the best one at that moment according to the agent beliefs. Thus, for each intention, a proper intention revision is defined taking into account also the priority of each of them. Indeed, once some conditions are satisfied for a certain intention, this si return as the best one and the intention revision is interrupted. Therefore, the `selectBestIntention()` function is structured as follows.

  // TODO: LLMGreenRedLightIntention

  // TODO: LLMGoToIntention

  + If the agent is achieving a GoPutDownIntention, check if, not so far from the current path, a parcel with a relevant score exists. If so, estimate the values of the lower carried parcel and of the target parcel at the time the pick up should be executed. If at that time the target parcel will have a higher score that the carried one, going to pick it up is convenient and *DeviateAndPickUpIntention* is returned. Note that our agent is very fast so the estimated difference is negligible, but we decided to implement it anyway as a proper way of working.

  + If the agent has just picked up a parcel, select a random red tile from the pre-computed weighted paths of the green tile (from which the agent just picked up the parcel), and return *GoPutDownIntention*.

  + If the agent is not carrying any parcel, select the parcel with the highest score, greater than the minimum acceptable, among all those the agent remembers and sees (if any). Then, return *GoPickUpIntention*.

  + If neither a GoPickUpIntention nor a GoPutDownIntention is in the queue, select a radom green tile and return *GoToIntention* (either from the pre-computed weighted paths of the red tiles the agent just delivered on, or just `Math.random()` among all green tiles).




  // We decided to split the plans into basics actions, and in some cases combine them in order to build more complex plans. The fundamental ones are the following.

  = Planner <sec-planner>

  = LLM <sec-llm>
]
