#import "lib/common.typ": agentName, course
#import "lib/reportLib.typ": docBody, firstPage, indexPage

#firstPage(agentName)

#indexPage()

#let Astar = $A^*$

#docBody[
  // #figure(
  //   image(
  //     "path",
  //     width: 50%,
  //   ),
  //   caption: [test],
  // )

  // #figure(
  //   table(
  //     columns: (50%, 50%),
  //     [], [],
  //   ),
  //   caption: [test],
  // )

  = BDI agent

  The BDI agent is composed by a class dedicated to manage its beliefs, a set of classes to define the intentions and plans, and the actual `bdi_agent.js` that implements the beliefs set up and update, intention revision, intention storage and plan execution.

  == Beliefs

  == Intentions

  We defined the following types of intentions that the agent can create according to its beliefs.

  - *GoToIntention* - the desire of reaching a specific tile.

  - *DeviateUsingAStarIntention* - the desire of requesting to the internal #Astar algorithm a new path, because the one selected by the agent is no more practicable.

  - *DeviateUsingPlannerIntention* - the desire of requesting to the planner a new path, because the one selected by the agent is no more practicable. The planner involvement is explained in details in @sec-planner.

  - *GoPickUpIntention* - the desire of picking up a parcel at a specific tile.

  - *GoPutDownIntention* - the desire of deliverying all the parcel the agent is carrying on a specific red tile.

  - *DeviateAndPickUpIntention* - the desire of picking up a parcel while the agent is going to put down others. In some cases the agent can pick up a parcel that will increase the score with a simple small change in the path, without wasting much time.

  Besides BDI agent intentions, generated by the agent itself, also the LLM agent (explained in details in @sec-llm), can provide the following new intentions.

  - *LLMGoToIntention*

  - *LLMGoPutDownIntention*

  - *LLMGreenRedLightIntention*

  A `intentionPlanQueue` queue is defined in order to store the pairs of selected intentions and the corresponding plans. The first element of the queue is executed by the agent.

  === Intention revision

  After the beliefs are set, an interval of 100 milliseconds generates a new intention, the best one at that moment according to the agent beliefs. Thus, for each intention, a proper intention revision is defined taking into account also the priority of each of them. Indeed, once some conditions are satisfied for a certain intention, this si return as the best one and the intention revision is interrupted. Therefore, the `selectBestIntention()` function is structured as follows.

  + If the LLM agent provided a *LLMGreenRedLightIntention*, this takes the maximum priority because it belongs to the level 3 tasks, and so it should give a very large reward.

  + If the LLM agent supplied a *LLMGoToIntention*, the agent evaluates the convenience of the deviation. If the agent discards the LLM intention, it forwards it to the other agent (the coordination is explained in details in @sec-coordination)

  // TODO: teo, LLMGoPutDown?

  + If the agent is achieving a GoPutDownIntention, check if, not so far from the current path, a parcel with a relevant score exists. If so, estimate the values of the lower carried parcel and of the target parcel at the time the pick up should be executed. If at that time the target parcel will have a higher score that the carried one, going to pick it up is convenient and *DeviateAndPickUpIntention* is returned. Note that our agent moves very fast so the estimated difference is negligible, but we decided to implement it anyway as a proper way of working.

  + If the agent has just picked up a parcel, select a random red tile from the pre-computed weighted paths of the green tile (from which the agent just picked up the parcel), and return *GoPutDownIntention*.

  + If the agent is not carrying any parcel, select the parcel with the highest score, greater than the minimum acceptable, among all those the agent remembers and sees (if any). Then, return *GoPickUpIntention*.

  + If neither a GoPickUpIntention nor a GoPutDownIntention is in the queue, select a radom green tile and return *GoToIntention* (either from the pre-computed weighted paths of the red tiles the agent just delivered on, or just `Math.random()` among all green tiles).

  Finally, if the selected best intention is not already present in the queue, the current intention is stopped and the new intention is pushed together with the corresponding plan. If the current intention was a GoToIntention, it is also popped due to its lowest priority. Then, the (new) current plan is executed and popped once it finishes. If the completed plan was a deviation and the current one is a GoPutDownPlan, the path of latter is updated keeping the same destination but with a new start point, the tile on which there was the parcel that caused the deviation.

  == Plans

  We decided to split the plans into basics actions, and then combine them in order to build more complex plans. The fundamental steps are the following.

  - *GoToPlan* - calculates a path from the agent position to a specified tile. According to the situation, it can use either an internal algorithm (#Astar in our case) or the planner. Once the path is computed, at each step the next tiles in front of the agent are checked to detect any obstacle (e.g. another agent or a crate). In order to avoid collisions and accumulate penalties, a deviation is computed in advance from the tile immediately before the obstacle. The tile of the obstacle is temporarily obscured (type 0) such that the path finder algorithm ignores it.

  - *DeviateUsingAStarPlan* - calculates a path from a certain tile to a specified destination using the $A^*$ algorithm. It is used as a sub-plan in GoToPlan.

  - *DeviateUsingPlannerPlan* - calculates a path from a certain tile to a specified destination using the planner. It is used as a sub-plan in GoToPlan when the agent runs into a crate.

  - *GoPickUpPlan* - instantiates a GoToIntention and a GoToPlan as sub-intention and sub-plan to reach a parcel, then performs an `emitPickp()`.

  - *GoPutDownPlan* - similar to GoPickUpPlan but performs an `emitPutdown()` at the end.

  - *DeviateAndPickUpPlan* - uses GoPickUpPlan as sub-plan, and in addition it adopts #Astar to compute in advance the path from the parcel to the actual destination.

  - *LLMGreenRedLightPlan* - masks the set of tiles allowed by the prompt (e.g. only odd-numbered rows) and instantiates a GoToPlan to reach the closest available tile.

  Each plan contains an `isApplicable(intention)` function used by the agent to verify which plan can handle which intention, then an `execute(intention)` method that actually performs the plan. This constantly checks if the agent requested to stop the plan (because the current intention changed): the `isStopped` variable is set to true, but the agent has to wait that also `isRunning` is set to false, namely the plan actually stopped. Since a check cannot be performed at every frame, a bit of delay is inevitable.

  = Planner <sec-planner>

  = LLM <sec-llm>

  == BDI agents coordination <sec-coordination>
]
